---
- name: Deploy Docker Container
  hosts: all
  become: true
  vars:
    docker_image: "ashmizashah/docker:latest"
  tasks:
    - name: Ensure Docker is installed
      ansible.builtin.command:
        cmd: "yum install -y docker"
